version: '3.8'
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: learning_app
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/learning_app
  

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend