services:
  - type: web
    name: backend-service
    env: node
    buildCommand: npm install && npm run build -w backend
    startCommand: npm run start -w backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: project-db
          property: connectionString

  - type: web
    name: frontend-service
    env: node
    buildCommand: np  m install && npm run build -w frontend
    startCommand: npm run start -w frontend
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://backend-service.onrender.com

databases:
  - name: project-db
    databaseName: mydb
    user: postgres